### PR TITLE
fix(promise): fix #88

### LINKED ISSUE #88: Do not enable longStackTraces, consider using Promise.getNewLibraryCopy
Should not globally set `longStackTraces` option from bluebird (https://github.com/beardon/mws-api/blob/master/lib/client.js#L15) because it will be set in bluebird singleton instance itself, forcing my or any project to have this enabled even in the production environment. Which apparently it can have a 2x-3x performance impact http://bluebirdjs.com/docs/api/promise.config.html#comment-3322469547

Consider using `Promise.getNewLibraryCopy` http://bluebirdjs.com/docs/api/promise.getnewlibrarycopy.html to create a custom instance and enable `longStackTraces` to that instance.

```js
const Promise = require('bluebird');
console.log(Promise.hasLongStackTraces()); // false (bluebird's default)
const mws = require('mws-api');
console.log(Promise.hasLongStackTraces()); // true (after importing mws-api)
```

### PR DESCRIPTION
**Pull request by dciccale**

### CODE REVIEW

**Comment by tyscorp** [comment]
Do we want to do this, or just require bluebird normally and let the user decide whether they want long stack traces or not?

**Comment by dciccale** [comment]
Hmm.. ok, maybe this was not in the scope of this fix. This was just intended to keep everything as is, but without modifying the outside world.

I guess having long traces as a Boolean option should be done as a separate feature maybe?

**Comment by dciccale** [comment]
Or I can do it in this same PR :) do you have any suggestions on how it could look like?

**Comment by tyscorp** [comment]
We can do this for now.

To leave it up to the user, we would just require bluebird as normal and leave out the `Promise.config`. The user would just do `Promise.config` on their instance to enable it on our instance also.

**Review by tyscorp — APPROVED** [review]

**Comment by dciccale** [comment]
I totally agree with you, lets remove it then.

**Pull request closed without merging**
