### PR TITLE
fix FBA outbound shipping

### PR DESCRIPTION
**Pull request by florianbepunkt**
fixes mws.FulfillmentOutboundShipment.CreateFulfillmentOrder(), moved the parameter conversion necessary for FBA into the request function

### CODE REVIEW

**Comment by florianbepunkt** [comment]
please ignore the first commit, messed something up. second commit should be good for review.

**Comment by dciccale** [comment]
@florianbepunkt why there are 23 files marked as changed when there were actually only 2 changed? I think it could be a line ending change, but not sure. Are you using some git client?

Please correct the issue, or open a new PR with only the changes you meant to do.

**Comment by florianbepunkt** [comment]
@dciccale using the github desktop client on mac os, so yes, probably a line ending issue. I'll try to correct it when I have more time but it may be a while I'm afraid

**Comment by matheusvellone** [comment]
Looks like it's related to file permissions that were 644 and was replaced with 777 when commited.
Changing them back to 644 with a `chmod -R 644 <project-dir>` should fix their permissions and may not be listed as a file changed

**Comment by WeeJeWel** [comment]
@florianbepunkt Thank you for your work, the code works very well in my implementation!

I hope this PR can be merged eventually, because now we have to resort to linking a github repo in the `package.json`, which feels... dirty.

**Comment by florianbepunkt** [comment]
@WeeJeWel you're welcome. although I would recommend using PR #98

**Pull request closed without merging**
