### PR TITLE
feat(lib): version 2.1.0 allow multiple messages on OrderFulfillment

### PR DESCRIPTION
**Pull request by dciccale**
Here is a description of the changes and why:

**Dependencies**
Replaced 2 dependencies `xml` and `xml2json`  in favor of https://npmjs.com/package/xml2js 

This has several advantages
- Less deps
- pure JavaScript parser
- does not rely on C code which in turns, gives slower installation time of mws-api since it has to compile node-expat. 
- super faster installation and does not require to have `make`, `gcc`, `g++` and `python` installed in the machine. (useful when building inside a Docker container and very appreciated having slim images)
- xml2js has 6million downloads/mo on NPM way more than all the other dependencies combined. And it is very well maintained. It basically uses `sax` and `xmlbuilder` deps. Check them out.

**Multiple messages**
Other reason for this replacement, is that `xml2js` automatically recognizes arrays or simple objects, meaning we can now pass multiple messages (array of objects) or only 1 (just an object) and it will work as before.

To create multiple messages just pass an array of them like this:

```js
const FeedContent = Feeds._POST_ORDER_FULFILLMENT_DATA_([{
    MessageID: 1,
    MerchantOrderID: 1234567,
    MerchantFulfillmentID: 1234567,
    FulfillmentDate: '2002-05-01T15:36:33-08:00',
    CarrierCode: 'UPS',
    ShippingMethod: 'Second Day',
    ShipperTrackingNumber: '1234567890'
}, {
    MessageID: 2,
    MerchantOrderID: 9876543,
    MerchantFulfillmentID: 9876543,
    FulfillmentDate: '2002-05-01T16:30:33-08:00',
    CarrierCode: 'DHL',
    ShippingMethod: 'Second Day',
    ShipperTrackingNumber: '1234567890'
}]);
```

**Breaking changes**
**EDIT:** There are no breaking changes.

I have also removed an unnecessary merge of data when creating the envelope to count the message id. This should be taken care of the developer when sending the data and not hidden in the implementation since it can bring confusion.

**Version**
~Since this is breaking, I bumped the version to 3.0.0~
Is not breaking now, guess I should increase `minor` version instead.

Sorry for doing this many changes :)

### CODE REVIEW

**Comment by dciccale** [comment]
Fixes #54

**Comment by dciccale** [comment]
@tyscorp could you review it?

**Comment by tyscorp** [comment]
LGTM!

@aaronbean will have to merge/release, though.

**Comment by dciccale** [comment]
Ok, thanks. We should dramatically increase code coverage though. We are heavily using this library on our company and probably will be spending some time on it.

**Comment by dciccale** [comment]
*NOTE*: This multiple message feature is only allowed on `_POST_ORDER_FULFILLMENT_DATA_` for now. Since the api has remained the same on all other methods. Which should be implemented in following releases

**Comment by BarryCarlyon** [comment]
The test of this is broken and the feeds result in a syntax/xml formatting problem when processed by amazon.

As the MerchantIdentifier is moved from the Header to the Message… or just omitted all together.

I'm investigating and will probably adjust my current PR at #82 to fix this/see whats what

**Comment by dciccale** [comment]
@BarryCarlyon  I don't see where the MerchantIdentifier has been moved to the message. Could you specify the line?

**Comment by BarryCarlyon** [comment]
@dciccale sorry my test code somewhere spat out a bad XML. I'm checking whats messed up right now.

And I'm rechecking the amazon XSD's against my XML

**Comment by BarryCarlyon** [comment]
Currently all the tests for `_POST_ORDER_FULFILLMENT_DATA_` omit a `<MerchantIdentifer>` key, so the test passes, but when throwing this XML at amazon it rejects it becuase the `<Header>` is missing the `<MerchantIdentifer>` key. (Granted this test was using a `_POST_ORDER_ACKNOWLEDGEMENT_DATA_` XML packet, but the XSD's at https://images-na.ssl-images-amazon.com/images/G/01/rainier/help/xsd/release_1_9/amzn-header.xsd have the MerchantIdentifier as a string (and not a minOccurs 0 so it's required)

**Comment by dciccale** [comment]
Hmm I am successfully using the previous version. Maybe I broke something on my PR. Will check where the difference is, and if I find something will bring the correct code back as a fix. Will check that in following days, unless you want to do the fix

**Comment by BarryCarlyon** [comment]
I'll take a stab at it at work tomorrow, since planning to use the module for work. So need it fixed :-P

**Pull request merged**
